name: GT7 Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Dependencies
      run: sudo apt install build-essential bc bison flex libssl-dev curl clang git lz4 libncurses-dev unzip openssl libelf-dev -y
    - name: Compile
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export KBUILD_BUILD_USER=Luki2421
        export KBUILD_BUILD_HOST=GT7
        make O=out ace5_defconfig
        make -j$(nproc) O=out CC=clang
    - name: Upload Image
      uses: actions/upload-artifact@v3
      with:
        name: Image
        path: out/arch/arm64/boot/Image
